import { Button, Center, HStack } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import CustomLink from '../components/UI/CustomLink';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Appliqa</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Center h='100vh'>
          <HStack>
            <CustomLink href='/login'>
              <Button colorScheme={'green'}>Go to login</Button>
            </CustomLink>

            <CustomLink href='/goals'>
              <Button colorScheme={'green'}>Go to dashboard</Button>
            </CustomLink>
          </HStack>
        </Center>
      </main>
    </>
  );
};

export default Home;
