import { Center, Text } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { HiOutlineCollection } from 'react-icons/hi';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>hi</main>
    </>
  );
};

export default Home;
